esphome:
  name: soil-sensor-teros-12-on-esp32
  includes:
   
  libraries:
    - EspSoftwareSerial
    
external_components:
  - source: 
      type: local
      path: components
    components: [soil_sensor_teros12]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Bbox-727DF9A6"
  password: "c7HwHdEL33bhCJ4fVm"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:

# TEROS 12 Soil Sensor 
soil_sensor_teros12:
  - id: tero12
    pin_data: 26 # pin where the sensor data is connected 
    scan_mode: # Switch to scan the bus on found SDI devices. The switch is optional when you know the sensor address
      name: "Scan Switch"
    address: 1  # address of the sensor
    
    temperature:  # Soil temperature 
      name: "Soil temperature"
    
    ec: # Electrical Conductivity
      name: "Soil EC"
    vwc:  # Volumetric Water Content
      name: "Soil Volumetric Water Content"

    update_interval: 60s # update interval of the measurement 

#sensors:
web_server:
  port: 80
